apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog-miyaoo
resources:
  - ../../base
  - ingress.yaml
# ArgoCD Image Updater が main push ごとに newTag を自動更新する
images:
  - name: wp-miyaoo:latest
    newName: ghcr.io/citrus171/wp-miyaoo
    newTag: sha-c6aa15b
